export const FILTER_DEFAULT_VALUES = {
    GENRE_VALUE: 'all',
    AUTHOR_VALUE: 'all',
    PAGES_VALUE: 0,
    YEAR_VALUE: 1800
}

export const LIBRARY_DEFAULT_VALUES = {
    READING_LIST_VALUE: [],
    TOTAL_READING_VALUE: 0,
    AVAILABLE_LIST_VALUE: [],
    TOTAL_AVAILABLE_VALUE: 0
}

export const LIBRARY_ACTION_TYPES = {
    SET_INITIAL_LIBRARY_LIST: 'SET_INITIAL_LIBRARY_LIST',
    ADD_TO_READING_LIST: 'ADD_TO_READING_LIST',
    REMOVE_FROM_READING_LIST: 'REMOVE_FROM_READING_LIST'
}

export const FILTER_ACTION_TYPES = {
    UPDATE_GENRE_FILTER: 'UPDATE_GENRE_FILTER',
    UPDATE_AUTHOR_FILTER: 'UPDATE_AUTHOR_FILTER',
    UPDATE_PAGES_FILTER: 'UPDATE_PAGES_FILTER',
    UPDATE_YEAR_FILTER: 'UPDATE_YEAR_FILTER'
}

export const THEME_MODES = {
    DARK: 'dark',
    LIGHT: 'light'
}

export const THEME_LOCAL_STORAGE = 'user-theme'
